#Validação cruzada e tunning de hiperparametro
---
**Aula Prática 19**: Validação cruzada e tunning de hiperparâmetro


**Objetivo**: Identificar o melhor conjunto de hiperparâmetros com validação cruzada.


Banco de dados:


**Breast cancer wisconsin dataset**


Disponível via sklearn


> Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass.  They describe characteristics of the cell nuclei present in the image.
>
> 1) ID number
>
> 2) Diagnosis (0 = malignant, 1 = benign)
>
> 3-32)
>
> Ten real-valued features are computed for each cell nucleus:
>
> a) radius (mean of distances from center to points on the perimeter)
>
> b) texture (standard deviation of gray-scale values)
>
> c) perimeter
>
> d) area
>
> e) smoothness (local variation in radius lengths)
>
> f) compactness (perimeter^2 / area - 1.0)
>
> g) concavity (severity of concave portions of the contour)
>
> h) concave points (number of concave portions of the contour)
>
> i) symmetry
>
> j) fractal dimension ("coastline approximation" - 1)

##Import das principais funções e leitura dos dados


---

In [9]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [2]:
data = datasets.load_breast_cancer()

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [4]:
target = pd.DataFrame(data.target, columns=['Target'])
df = pd.concat([df, target], axis=1)

In [5]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [6]:
df.shape

(569, 31)

In [7]:
df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int32
dtype: object

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mean radius,569.0,14.127292,3.524049,6.981000,11.700000,13.370000,15.780000,28.11000
mean texture,569.0,19.289649,4.301036,9.710000,16.170000,18.840000,21.800000,39.28000
mean perimeter,569.0,91.969033,24.298981,43.790000,75.170000,86.240000,104.100000,188.50000
mean area,569.0,654.889104,351.914129,143.500000,420.300000,551.100000,782.700000,2501.00000
mean smoothness,569.0,0.096360,0.014064,0.052630,0.086370,0.095870,0.105300,0.16340
mean compactness,569.0,0.104341,0.052813,0.019380,0.064920,0.092630,0.130400,0.34540
mean concavity,569.0,0.088799,0.079720,0.000000,0.029560,0.061540,0.130700,0.42680
mean concave points,569.0,0.048919,0.038803,0.000000,0.020310,0.033500,0.074000,0.20120
mean symmetry,569.0,0.181162,0.027414,0.106000,0.161900,0.179200,0.195700,0.30400
mean fractal dimension,569.0,0.062798,0.007060,0.049960,0.057700,0.061540,0.066120,0.09744
radius error,569.0,0.405172,0.277313,0.111500,0.232400,0.324200,0.478900,2.87300
texture error,569.0,1.216853,0.551648,0.360200,0.833900,1.108000,1.474000,4.88500
perimeter error,569.0,2.866059,2.021855,0.757000,1.606000,2.287000,3.357000,21.98000
area error,569.0,40.337079,45.491006,6.802000,17.850000,24.530000,45.190000,542.20000
smoothness error,569.0,0.007041,0.003003,0.001713,0.005169,0.006380,0.008146,0.03113
compactness error,569.0,0.025478,0.017908,0.002252,0.013080,0.020450,0.032450,0.13540
concavity error,569.0,0.031894,0.030186,0.000000,0.015090,0.025890,0.042050,0.39600
concave points error,569.0,0.011796,0.006170,0.000000,0.007638,0.010930,0.014710,0.05279
symmetry error,569.0,0.020542,0.008266,0.007882,0.015160,0.018730,0.023480,0.07895
fractal dimension error,569.0,0.003795,0.002646,0.000895,0.002248,0.003187,0.004558,0.02984
worst radius,569.0,16.269190,4.833242,7.930000,13.010000,14.970000,18.790000,36.04000
worst texture,569.0,25.677223,6.146258,12.020000,21.080000,25.410000,29.720000,49.54000
worst perimeter,569.0,107.261213,33.602542,50.410000,84.110000,97.660000,125.400000,251.20000
worst area,569.0,880.583128,569.356993,185.200000,515.300000,686.500000,1084.000000,4254.00000
worst smoothness,569.0,0.132369,0.022832,0.071170,0.116600,0.131300,0.146000,0.22260
worst compactness,569.0,0.254265,0.157336,0.027290,0.147200,0.211900,0.339100,1.05800
worst concavity,569.0,0.272188,0.208624,0.000000,0.114500,0.226700,0.382900,1.25200
worst concave points,569.0,0.114606,0.065732,0.000000,0.064930,0.099930,0.161400,0.29100
worst symmetry,569.0,0.290076,0.061867,0.156500,0.250400,0.282200,0.317900,0.66380
worst fractal dimension,569.0,0.083946,0.018061,0.055040,0.071460,0.080040,0.092080,0.20750
Target,569.0,0.627417,0.483918,0.000000,0.000000,1.000000,1.000000,1.00000

### Separação do banco entre treino e teste
O primeiro passo para se treinar um modelo é separar o banco entre treino e teste. Para isso utilizaremos a função train_test_split




``` python
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.3, random_state=15)
```
No exemplo acima X é um dataframe contendo as features do modelo e Y um dataframe com a variável target.




O parâmetro test_size controla o percentual de dados que será utilizado para teste.




O parâmetro random_state controla a aleatoriedade da geração do dado, permitindo que ao executar o código seja gerado os mesmos bancos de treino e teste.




É importante separar o banco entre treino e teste, pois utilizaremos o banco de treino para treinar modelos e o banco de teste para avaliar os modelos.


### Validação cruzada
Para realizar a validação cruzada separamos o banco de treino em pequenos grupos chamados folds, cada um será utilizado como um banco de treino para avaliarmos a consistência do modelo.


``` python
from sklearn.model_selection import cross_validate
scoring = ['precision_macro', 'recall_macro']
scores = cross_validate(model, X_train, Y_train, scoring=scoring)
```


### Tuning de hiperparâmetro
Para achar o hiperparâmetro que dê o melhor resultado devemos testar diferentes combinações de hiperparâmetro para achar o melhor. Há três algoritmos para fazer:


* GridSearch: Busca por todos os possíveis valores passados pelo usuário.
* RandomSerch: Busca aleatória em um intervalo de valores determinado
* BayesianOptimization: Busca através de um otimizador.


No código a seguir iremos utilizar o GridSearch com validação cruzada


``` python
from sklearn.model_selection import GridSearchCV
parameters = {'parâmetro 1' : [0.1, 0.03, 0.01],
              'parâmetro 2': [100, 500, 50]}


clf = GridSearchCV(model, parameters)
clf.fit(X_train, Y_train)
clf.best_params_
pd.DataFrame(clf.cv_results_)
```

No código a seguir iremos utilizar o RandomSearch com validação cruzada


``` python
from sklearn.model_selection import RandomizedSearchCV
parameters = {'parâmetro 1' : scipy.stats.expon(scale=.1),
              'parâmetro 2': scipy.stats.uniform(50, 500)}


clf = RandomizedSearchCV(model, parameters)
clf.fit(X_train, Y_train)
clf.best_params_
pd.DataFrame(clf.cv_results_)
```

In [11]:
X = pd.DataFrame(data.data, columns=data.feature_names)
Y = data.target

### Exercício:


* Separe o banco entre treino e teste. Use 30% do banco para teste. Faça a quebra com todas as variáveis.
* Utilizando um classificador xgboost faça:
* Faça a validação cruzada do modelo, qual o valor médio de precisão macro
* Faça uma busca, utilizando grid search, nos parâmetros learning_rate com valores de 0.1, 0.05 e 0.01 e n_estimators com valores de 100, 500, 50. Qual é a melhor configuração?
* Aplique essa configuração no modelo e avalie os resultados.

#### Solução

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=15
)

In [14]:
from xgboost import XGBClassifier

In [15]:
model_xgb = XGBClassifier(objective='binary:logistic')

In [18]:
from sklearn.model_selection import cross_validate

scoring = ["precision_macro", "recall_macro"]
scores = cross_validate(model_xgb, X_train, Y_train, scoring=scoring)

In [19]:
scores

{'fit_time': array([0.27284384, 0.14691377, 0.12392879, 0.11593509, 0.10794044]),
 'score_time': array([0.01099324, 0.01499438, 0.01099348, 0.01299   , 0.01199102]),
 'test_precision_macro': array([0.98076923, 0.9532967 , 0.9532967 , 0.98333333, 0.90292208]),
 'test_recall_macro': array([0.96666667, 0.94      , 0.94      , 0.99      , 0.92210884])}

In [22]:
scores['test_precision_macro'].mean()

0.9547236097236098

In [24]:
from sklearn.model_selection import GridSearchCV

parameters = {"learning_rate": [0.1, 0.03, 0.01], "n_estimators": [100, 500, 50]}

clf = GridSearchCV(model_xgb, parameters)
clf.fit(X_train, Y_train)

GridSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'learning_rate': [0.1, 0.03, 0.01],
                         'n_estimators': [100, 500, 50]})

### Exercício:


* Utilizando um classificador xgboost faça:
* Faça uma busca, utilizando random search, nos parâmetros learning_rate com distribuição exponencial com parâmetro 0.01 e n_estimators com distribuição uniforme de 50 a 500 (utilizar a distribuição randint). Qual é a melhor configuração? Faça o número de tentativas igual a 9
* Aplique essa configuração no modelo e avalie os resultados.

#### Solução

In [26]:
!pip install optuna

Collecting optuna
  Downloading optuna-3.6.1-py3-none-any.whl (380 kB)
Collecting colorlog
  Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Requirement already satisfied: sqlalchemy>=1.3.0 in d:\users\renan lemes\anaconda3\lib\site-packages (from optuna) (1.4.32)
Requirement already satisfied: numpy in d:\users\renan lemes\anaconda3\lib\site-packages (from optuna) (1.26.4)
Requirement already satisfied: PyYAML in d:\users\renan lemes\anaconda3\lib\site-packages (from optuna) (6.0)
Requirement already satisfied: tqdm in d:\users\renan lemes\anaconda3\lib\site-packages (from optuna) (4.64.0)
Requirement already satisfied: packaging>=20.0 in d:\users\renan lemes\anaconda3\lib\site-packages (from optuna) (21.3)
Requirement already satisfied: alembic>=1.5.0 in c:\users\renan lemes\appdata\roaming\python\python39\site-packages (from optuna) (1.13.0)
Requirement already satisfied: typing-extensions>=4 in d:\users\renan lemes\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (4.1.1)
Requirement already satisfied: Mako in c:\users\renan lemes\appdata\roaming\python\python39\site-packages (from alembic>=1.5.0->optuna) (1.3.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in d:\users\renan lemes\anaconda3\lib\site-packages (from packaging>=20.0->optuna) (3.0.4)
Requirement already satisfied: greenlet!=0.4.17 in d:\users\renan lemes\anaconda3\lib\site-packages (from sqlalchemy>=1.3.0->optuna) (1.1.1)
Requirement already satisfied: colorama in c:\users\renan lemes\appdata\roaming\python\python39\site-packages (from colorlog->optuna) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\users\renan lemes\anaconda3\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.0.1)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.8.2 optuna-3.6.1

In [27]:
import optuna
from statistics import mean


def objective(trial):
    xg_lr = trial.suggest_float("xg_lr", 0.01, 0.1, log=True)
    xg_est = trial.suggest_int("xg_est", 50, 500, log=False)

    classifier = XGBClassifier(
        objective="binary:logistic", learning_rate=xg_lr, n_estimators=xg_est
    )
    scores = cross_validate(classifier, X_train, Y_train, scoring="accuracy")
    return mean(scores["test_score"])

In [28]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10)

[I 2024-05-07 21:02:00,874] A new study created in memory with name: no-name-b5bc1c14-587e-485c-afbe-8007bb276bed
[I 2024-05-07 21:02:01,934] Trial 0 finished with value: 0.9421835443037975 and parameters: {'xg_lr': 0.050632022452201816, 'xg_est': 66}. Best is trial 0 with value: 0.9421835443037975.
[I 2024-05-07 21:02:05,605] Trial 1 finished with value: 0.9422151898734177 and parameters: {'xg_lr': 0.01178216013069391, 'xg_est': 250}. Best is trial 1 with value: 0.9422151898734177.
[I 2024-05-07 21:02:10,877] Trial 2 finished with value: 0.952246835443038 and parameters: {'xg_lr': 0.017944781292539246, 'xg_est': 438}. Best is trial 2 with value: 0.952246835443038.
[I 2024-05-07 21:02:16,384] Trial 3 finished with value: 0.949746835443038 and parameters: {'xg_lr': 0.010905260156084465, 'xg_est': 433}. Best is trial 2 with value: 0.952246835443038.
[I 2024-05-07 21:02:18,408] Trial 4 finished with value: 0.949746835443038 and parameters: {'xg_lr': 0.08765834832005569, 'xg_est': 98}. Best is trial 2 with value: 0.952246835443038.
[I 2024-05-07 21:02:22,611] Trial 5 finished with value: 0.9472151898734177 and parameters: {'xg_lr': 0.01295946612054092, 'xg_est': 321}. Best is trial 2 with value: 0.952246835443038.
[I 2024-05-07 21:02:25,614] Trial 6 finished with value: 0.949746835443038 and parameters: {'xg_lr': 0.020884450189847907, 'xg_est': 281}. Best is trial 2 with value: 0.952246835443038.
[I 2024-05-07 21:02:28,172] Trial 7 finished with value: 0.954746835443038 and parameters: {'xg_lr': 0.06279154340453338, 'xg_est': 431}. Best is trial 7 with value: 0.954746835443038.
[I 2024-05-07 21:02:30,585] Trial 8 finished with value: 0.949746835443038 and parameters: {'xg_lr': 0.09079285625774731, 'xg_est': 447}. Best is trial 7 with value: 0.954746835443038.
[I 2024-05-07 21:02:33,762] Trial 9 finished with value: 0.949746835443038 and parameters: {'xg_lr': 0.031110329144247856, 'xg_est': 389}. Best is trial 7 with value: 0.954746835443038.

* Utilizando um classificador RandomForest faça:
* Faça uma busca, utilizando random search, nos parâmetros max_depth com distribuição uniforme discreta de 2 a 10 e n_estimators com distribuição uniforme de 50 a 500. Qual é a melhor configuração? Faça o número de tentativas igual a 9
* Aplique essa configuração no modelo e avalie os resultados.

#### Solução

Optuna

Para utilizar a otimização bayesiana iremos usar o pacote Optuna.

Para a utilização desse pacote devemos considerar os seguinte passos:
1. Definir uma função objetivo
2. Criar sugestão dos valores do hiperparâmetro utilizando o módulo trial
3. Criar um objeto de estudo

``` python
import optuna

# 1. Define an objective function to be maximized.
def objective(trial):

    # 2. Suggest values for the hyperparameters using a trial object.
    rf_max_depth = trial.suggest_int('rf_max_depth', 2, 32, log=True)
    classifier_obj = sklearn.ensemble.RandomForestClassifier(max_depth=rf_max_depth, n_estimators=10)
    ...
    return accuracy

# 3. Create a study object and optimize the objective function.
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)
```

* Utilizando um classificador xgboost faça:
* Faça uma busca, utilizando optuna, nos parâmetros learning_rate com distribuição log uniform de 0.01 a 0.1 e n_estimators com distribuição uniforme de 50 a 500. Qual é a melhor configuração? Faça o número de tentativas igual a 9
* Aplique essa configuração no modelo e avalie os resultados.

[Link com documentação dos trial](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.suggest_float)

#### Solução